apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: esustellar-monitoring
resources:
  - grafana-deployment.yaml
configMapGenerator:
  - name: grafana-datasources
    files:
      - datasources/datasources.yaml
  - name: grafana-dashboard-files
    files:
      - dashboards/on-chain-events.json
      - dashboards/web-app-golden-signals.json
  - name: grafana-dashboards-provisioning
    files:
      - dashboards/dashboard-provisioning.yaml
