apiVersion: v1
kind: ConfigMap
metadata:
  name: esustellar-config
  namespace: esustellar-testnet
  labels:
    app: esustellar-web
    environment: testnet
data:
  NEXT_PUBLIC_SAVINGS_CONTRACT_ID: "CAGYPHW5QDEKCDKJXI5EQENRRBQSZDGDYPMQUF4MOGHCA63YWSMLPFUN"
  NEXT_PUBLIC_REGISTRY_CONTRACT_ID: "CDFH5MTVBX4NLCTL53N5XD5A3TIZ2O3KX65ZV7QG52TPP5X5KQLTFUC2"
  NEXT_PUBLIC_CONTRACT_ID: "CAGYPHW5QDEKCDKJXI5EQENRRBQSZDGDYPMQUF4MOGHCA63YWSMLPFUN"
