apiVersion: v1
kind: Service
metadata:
  name: esustellar-web
  namespace: esustellar-testnet
  labels:
    app: esustellar-web
    environment: testnet
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: esustellar-web
