#!/usr/bin/env bash
set -euo pipefail

# Contract error code reference generator (#873)
#
# Parses error enums from all contracts and generates a unified
# human-readable error reference at docs/error-reference.md.
#
# Usage:
#   ./scripts/generate-error-docs.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="$ROOT_DIR/docs/error-reference.md"
CONTRACTS_DIR="$ROOT_DIR/contracts"

echo "# EsuStellar Contract Error Reference" > "$OUTPUT"
echo "" >> "$OUTPUT"
echo "> Auto-generated by \`scripts/generate-error-docs.sh\`. Do not edit manually." >> "$OUTPUT"
echo ">" >> "$OUTPUT"
echo "> Re-generate: \`./scripts/generate-error-docs.sh\`" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Contract | Code | Error Name | Suggested UI Message |" >> "$OUTPUT"
echo "|----------|------|------------|---------------------|" >> "$OUTPUT"

# Suggested UI messages mapped by error name pattern
get_ui_message() {
  local name="$1"
  case "$name" in
    *ContributionTooLow*)    echo "Contribution amount is below the minimum (10 XLM)" ;;
    *ContributionTooHigh*)   echo "Contribution amount exceeds the maximum allowed" ;;
    *InvalidMemberCount*)    echo "Member count must be between 3 and 20" ;;
    *StartDateMustBeFuture*) echo "Start date must be in the future" ;;
    *StartDateTooFar*)       echo "Start date must be within one year" ;;
    *StartDateAlreadyPassed*) echo "Start date has already passed" ;;
    *GroupNotFound*)         echo "This group does not exist" ;;
    *GroupNotAccepting*)     echo "This group is not accepting new members" ;;
    *GroupIsFull*)           echo "This group is already full" ;;
    *AlreadyMember*)         echo "You are already a member of this group" ;;
    *GroupNotActive*)        echo "This group is not active yet" ;;
    *NotMember*)             echo "You are not a member of this group" ;;
    *MemberDefaulted*)       echo "This member has defaulted" ;;
    *AlreadyPaidThisRound*)  echo "You have already contributed this round" ;;
    *PaymentWindowClosed*)   echo "The payment window for this round is closed" ;;
    *RecipientNotFound*)     echo "No recipient found for this round" ;;
    *NoRecipientFound*)      echo "No recipient found" ;;
    *Overflow*)              echo "Arithmetic overflow occurred" ;;
    *ArithmeticOverflow*)    echo "Arithmetic overflow occurred" ;;
    *NotAdmin*)              echo "You do not have admin access" ;;
    *AdminOnly*)             echo "This action is restricted to administrators" ;;
    *GroupNotOpen*)          echo "This group is not open for joining" ;;
    *GroupIsPrivate*)        echo "This is a private group" ;;
    *RateLimited*)           echo "Too many requests. Please try again later" ;;
    *NotAllPaid*)            echo "Not all members have contributed yet" ;;
    *NoRefundAvailable*)     echo "No refund available" ;;
    *RoundNotStalled*)       echo "This round is not stalled" ;;
    *GroupPaused*)           echo "This group is currently paused" ;;
    *DataExpired*)           echo "Data has expired. Please refresh" ;;
    *AlreadyInitialized*)    echo "Contract is already initialized" ;;
    *MemberDataMissing*)     echo "Member data is missing" ;;
    *CatchUpRequired*)       echo "You need to catch up on missed contributions" ;;
    *NotDefaulted*)          echo "This member is not in default" ;;
    *InvalidRound*)          echo "Invalid round number" ;;
    *GroupIdAlreadyExists*)  echo "A group with this ID already exists" ;;
    *StringTooLong*)         echo "Input exceeds maximum length" ;;
    *NotAnAllowedMember*)    echo "You are not on the allowed members list" ;;
    *GroupAlreadyRegistered*) echo "This group is already registered" ;;
    *NotGroupAdmin*)         echo "You are not the admin of this group" ;;
    *UserNotInGroup*)        echo "User is not in this group" ;;
    *InvalidAddress*)        echo "Invalid contract address" ;;
    *MetadataMismatch*)      echo "Group metadata does not match on-chain state" ;;
    *NotAContract*)          echo "Address is not a deployed contract" ;;
    *AlreadyDelegate*)       echo "This delegate is already authorized" ;;
    *NotADelegate*)          echo "This address is not an authorized delegate" ;;
    *CannotDelegateToSelf*)  echo "You cannot delegate to yourself" ;;
    *RevocationFailed*)      echo "Failed to revoke delegation" ;;
    *AlreadyVoted*)          echo "You have already voted on this proposal" ;;
    *ProposalNotFound*)      echo "This proposal does not exist" ;;
    *VotingPeriodNotEnded*)  echo "Voting period has not ended yet" ;;
    *QuorumNotReached*)      echo "Quorum was not reached" ;;
    *ThresholdNotMet*)       echo "Passing threshold was not met" ;;
    *AlreadyFinalized*)      echo "This proposal has already been finalized" ;;
    *InvalidParameter*)      echo "Invalid parameter" ;;
    *CallerNotApproved*)     echo "This caller is not approved to send notifications" ;;
    *InsufficientBalance*)   echo "Insufficient fund balance" ;;
    *ClaimNotFound*)         echo "This claim does not exist" ;;
    *ClaimAlreadyProcessed*) echo "This claim has already been processed" ;;
    *InvalidAmount*)         echo "Invalid amount" ;;
    *)                       echo "An error occurred" ;;
  esac
}

found_contracts=0

for contract_dir in "$CONTRACTS_DIR"/*/; do
  contract_name=$(basename "$contract_dir")
  lib_file="$contract_dir/src/lib.rs"

  if [ ! -f "$lib_file" ]; then
    continue
  fi

  # Check if file has a #[contracterror] block
  if ! grep -q '#\[contracterror\]' "$lib_file" 2>/dev/null; then
    continue
  fi

  found_contracts=$((found_contracts + 1))
  echo "Processing: $contract_name"

  # Extract error variants with codes
  # Pattern: ErrorName = N,
  in_error_block=false
  while IFS= read -r line; do
    if echo "$line" | grep -q '#\[contracterror\]'; then
      in_error_block=true
      continue
    fi

    if [ "$in_error_block" = true ]; then
      # Match error variant lines like: ContributionTooLow = 1,
      if echo "$line" | grep -qE '^\s+\w+\s*=\s*[0-9]+'; then
        error_name=$(echo "$line" | sed 's/^[[:space:]]*//' | cut -d'=' -f1 | tr -d ' ')
        error_code=$(echo "$line" | sed 's/^[[:space:]]*//' | cut -d'=' -f2 | tr -d ',' | tr -d ' ')
        ui_message=$(get_ui_message "$error_name")
        echo "| $contract_name | $error_code | $error_name | $ui_message |" >> "$OUTPUT"
      fi

      # Stop at closing brace
      if echo "$line" | grep -q '^\s*}'; then
        in_error_block=false
      fi
    fi
  done < "$lib_file"
done

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "*Generated from $found_contracts contracts.*" >> "$OUTPUT"

echo "Generated error reference at $OUTPUT from $found_contracts contracts."
