#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Source of truth
DEPLOYMENT_INFO="${1:-$ROOT_DIR/deployment-info.json}"

if [ ! -f "$DEPLOYMENT_INFO" ]; then
  echo "Error: $DEPLOYMENT_INFO not found"
  echo "Usage: $0 [path/to/deployment-info.json]"
  exit 1
fi

REGISTRY_CONTRACT_ID=$(jq -r '.registry_contract_id' "$DEPLOYMENT_INFO")
SAVINGS_CONTRACT_ID=$(jq -r '.savings_contract_id' "$DEPLOYMENT_INFO")
DEPLOYED_NETWORK=$(jq -r '.network // "testnet"' "$DEPLOYMENT_INFO")
DEPLOYED_AT=$(jq -r '.deployed_at // empty' "$DEPLOYMENT_INFO")

echo "Syncing contract IDs from: $DEPLOYMENT_INFO"
echo "  Registry: $REGISTRY_CONTRACT_ID"
echo "  Savings:  $SAVINGS_CONTRACT_ID"
echo "  Network:  $DEPLOYED_NETWORK"
echo ""

# ──────────────────────────────────────────────
# 1. apps/web/.env.local
# ──────────────────────────────────────────────
WEB_ENV="$ROOT_DIR/apps/web/.env.local"
echo "Updating $WEB_ENV ..."
mkdir -p "$(dirname "$WEB_ENV")"
{
  if [ -f "$WEB_ENV" ]; then
    grep -v '^NEXT_PUBLIC_REGISTRY_CONTRACT_ID=' "$WEB_ENV" 2>/dev/null | \
    grep -v '^NEXT_PUBLIC_SAVINGS_CONTRACT_ID=' | \
    grep -v '^NEXT_PUBLIC_CONTRACT_ID=' || true
  fi
  echo "NEXT_PUBLIC_REGISTRY_CONTRACT_ID=$REGISTRY_CONTRACT_ID"
  echo "NEXT_PUBLIC_SAVINGS_CONTRACT_ID=$SAVINGS_CONTRACT_ID"
  echo "NEXT_PUBLIC_CONTRACT_ID=$SAVINGS_CONTRACT_ID"
} > "$WEB_ENV.tmp"
mv "$WEB_ENV.tmp" "$WEB_ENV"
echo "  OK"

# ──────────────────────────────────────────────
# 2. mobile/.env.{development,staging,production}
# ──────────────────────────────────────────────
update_mobile_env() {
  local ENV_FILE="$1"
  if [ ! -f "$ENV_FILE" ]; then
    echo "  Skipping $ENV_FILE (not found)"
    return
  fi
  echo "Updating $ENV_FILE ..."
  {
    grep -v '^EXPO_PUBLIC_REGISTRY_CONTRACT_ID=' "$ENV_FILE" 2>/dev/null | \
    grep -v '^EXPO_PUBLIC_SAVINGS_CONTRACT_ID=' || true
    echo "EXPO_PUBLIC_REGISTRY_CONTRACT_ID=$REGISTRY_CONTRACT_ID"
    echo "EXPO_PUBLIC_SAVINGS_CONTRACT_ID=$SAVINGS_CONTRACT_ID"
  } > "$ENV_FILE.tmp"
  mv "$ENV_FILE.tmp" "$ENV_FILE"
  echo "  OK"
}

update_mobile_env "$ROOT_DIR/mobile/.env.development"
update_mobile_env "$ROOT_DIR/mobile/.env.staging"
update_mobile_env "$ROOT_DIR/mobile/.env.production"

# Also update .env.example as a reference
if [ -f "$ROOT_DIR/mobile/.env.example" ]; then
  update_mobile_env "$ROOT_DIR/mobile/.env.example"
fi

# ──────────────────────────────────────────────
# 3. packages/shared/src/contracts.ts
# ──────────────────────────────────────────────
SHARED_CONTRACTS="$ROOT_DIR/packages/shared/src/contracts.ts"
echo "Generating $SHARED_CONTRACTS ..."
mkdir -p "$(dirname "$SHARED_CONTRACTS")"
cat > "$SHARED_CONTRACTS" <<CONTRACTS_EOF
// Auto-generated by scripts/sync-contract-ids.sh
// DO NOT EDIT MANUALLY

export const REGISTRY_CONTRACT_ID = '$REGISTRY_CONTRACT_ID'
export const SAVINGS_CONTRACT_ID = '$SAVINGS_CONTRACT_ID'

export const DEPLOYED_NETWORK = '$DEPLOYED_NETWORK'
export const DEPLOYED_AT = '$DEPLOYED_AT'
CONTRACTS_EOF
echo "  OK"

# ──────────────────────────────────────────────
# 4. environments/testnet/config/testnet.env
# ──────────────────────────────────────────────
TESTNET_ENV="$ROOT_DIR/environments/testnet/config/testnet.env"
if [ -f "$TESTNET_ENV" ]; then
  echo "Updating $TESTNET_ENV ..."
  {
    grep -v '^NEXT_PUBLIC_REGISTRY_CONTRACT_ID=' "$TESTNET_ENV" 2>/dev/null | \
    grep -v '^NEXT_PUBLIC_SAVINGS_CONTRACT_ID=' | \
    grep -v '^NEXT_PUBLIC_CONTRACT_ID=' || true
    echo "NEXT_PUBLIC_REGISTRY_CONTRACT_ID=$REGISTRY_CONTRACT_ID"
    echo "NEXT_PUBLIC_SAVINGS_CONTRACT_ID=$SAVINGS_CONTRACT_ID"
    echo "NEXT_PUBLIC_CONTRACT_ID=$SAVINGS_CONTRACT_ID"
  } > "$TESTNET_ENV.tmp"
  mv "$TESTNET_ENV.tmp" "$TESTNET_ENV"
  echo "  OK"
fi

# ──────────────────────────────────────────────
# 5. environments/testnet/k8s/configmap.yaml
# ──────────────────────────────────────────────
CONFIGMAP="$ROOT_DIR/environments/testnet/k8s/configmap.yaml"
if [ -f "$CONFIGMAP" ]; then
  echo "Updating $CONFIGMAP ..."
  sed -i "s|NEXT_PUBLIC_SAVINGS_CONTRACT_ID: \".*\"|NEXT_PUBLIC_SAVINGS_CONTRACT_ID: \"$SAVINGS_CONTRACT_ID\"|" "$CONFIGMAP"
  sed -i "s|NEXT_PUBLIC_REGISTRY_CONTRACT_ID: \".*\"|NEXT_PUBLIC_REGISTRY_CONTRACT_ID: \"$REGISTRY_CONTRACT_ID\"|" "$CONFIGMAP"
  sed -i "s|NEXT_PUBLIC_CONTRACT_ID: \".*\"|NEXT_PUBLIC_CONTRACT_ID: \"$SAVINGS_CONTRACT_ID\"|" "$CONFIGMAP"
  echo "  OK"
fi

echo ""
echo "Sync complete."
